development:
  adapter: postgresql
  encoding: unicode
  database: atestb_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: atestb_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: atestb_production
  pool: 5
  password:
