development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: atestb_development
  pool: 5
  username: wendigo
  password: gfhjkmkeyfnbr
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: atestb_test
  pool: 5
  username: wendigo
  password: gfhjkmkeyfnbr
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: atestb_production
  pool: 5
  username: wendigo
  password: gfhjkmkeyfnbr
  host: localhost
